title:              Clean Blog
email:              psj216@gmail.com
description:        테스트 블로그
author:             Seokjong Park
baseurl:            ""
url:                "https://seokjong.github.io/"

# Social Profiles
twitter_username:   
github_username:    seokjong
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
